### ISSUE TITLE
SyntaxError(s)

### ISSUE THREAD

**Issue by domenkozar** [miohtama/vvv#4] opened 2012-06-13 12:44 UTC
Getting distribution for 'vvv'.
SyntaxError: ('invalid syntax', ('build/bdist.linux-i686/egg/ghettoci/main.py', 321, 21, 'class Repo(metaclass=ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('build/bdist.linux-i686/egg/vvv/main.py', 393, 13, '    options : ("Validation options file. Default is validation-options.ya
ml", \'option\', \'o\', None, None, "validation-options.yaml"),\n'))

SyntaxError: ('invalid syntax', ('build/bdist.linux-i686/egg/vvv/plugin.py', 25, 23, 'class Plugin(metaclass=ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('build/bdist.linux-i686/egg/vvv/textlineplugin.py', 17, 39, 'class TextLinePlugin(Plugin, metaclass=ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('build/bdist.linux-i686/egg/vvv/scripts/addjsglobals.py', 150, 15, '    jsglobals : ("Comma separated list to globals to be a
dded", "positional", None, None, None, "GLOBALSLIST"),    \n'))

SyntaxError: ('invalid syntax', ('/home/ielectric/.buildout/eggs/tmp5j74oK/vvv-0.3.0-py2.7.egg/ghettoci/main.py', 321, 21, 'class Repo(metaclass=ABCMeta):\n')
)

SyntaxError: ('invalid syntax', ('/home/ielectric/.buildout/eggs/tmp5j74oK/vvv-0.3.0-py2.7.egg/vvv/main.py', 393, 13, '    options : ("Validation options file
. Default is validation-options.yaml", \'option\', \'o\', None, None, "validation-options.yaml"),\n'))

SyntaxError: ('invalid syntax', ('/home/ielectric/.buildout/eggs/tmp5j74oK/vvv-0.3.0-py2.7.egg/vvv/plugin.py', 25, 23, 'class Plugin(metaclass=ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('/home/ielectric/.buildout/eggs/tmp5j74oK/vvv-0.3.0-py2.7.egg/vvv/textlineplugin.py', 17, 39, 'class TextLinePlugin(Plugin, m
etaclass=ABCMeta):\n'))

SyntaxError: ('invalid syntax', ('/home/ielectric/.buildout/eggs/tmp5j74oK/vvv-0.3.0-py2.7.egg/vvv/scripts/addjsglobals.py', 150, 15, '    jsglobals : ("Comma
 separated list to globals to be added", "positional", None, None, None, "GLOBALSLIST"),    \n'))

Got vvv 0.3.0.

(using python2.7 and zc.buildout 1.5.2)

**Comment by miohtama** [comment] 2012-06-13 17:10
It clearly says in the installation instructions that this product is only compatible with Python 3 :)

However, Python 2.x port is underway.

**Comment by miohtama** [comment] 2012-06-13 17:10
Duplicate of #2

**Closed as completed by miohtama** 2012-06-13 17:10 UTC

**Comment by miohtama** [comment] 2012-06-26 10:17
All tests pass on Python 2.7 - please feel free to try out the trunk version

http://miohtama.github.com/vvv/installation.html#installing-trunk-version
